- name: HABIR
  image: HABIRH_with_shadow.png
  url: http://yongyuan.name/habir
  oneliner: Hashing Baseline for Image Retrieval
  role: Project Owner
  description: >
    I do the image retrieval research in early 2013. My mission is to design
    efficient hashing algorithm to map the semantic similar images to the similar codes.
    There are two main advantages using hashing method for image retrieval, i.e. storage and
    computation efficience. To let more researchers focus on design hashing algorithm, I have 
    built a hashing baseline, hoping this project can do some help for some researchers.
  technologies:
    - Matlab
    - Hashing
    - Image Retrieval

- name: PCVwithPython
  image: PCVH_with_shadow.png
  url: http://yongyuan.name/pcvwithpython
  oneliner: Programming Computer Vision with Python(Translate to Chinese)
  role: Main trainslator
  description: >
    I'm a big fun of Python. I think Python is one of the most elegant programming language
    I have known. It's a great power tool which can be used everywhere, such as write scripts,
    using Django for web developmentand do science computation. When I first meet the book <Programming 
    Computer Vision with Python>, I was attracted by the book. The content in this book is 
    quite rich and diverse and I can't bear to share the book to more people. So in my free time, I dived into
    the book and translate it into Chinese. Morover, I organized and supply the codes.
  technologies:
    - Python
    - Jekyll
    - Markdown




